#(1) Name : Qirui Sun
#(2) USC ID Number : 1140685892
#(3) USC Email : qiruisun@usc.ed
#(4) Submission Date : 02/07/2021

all:
	g++ -o step1 step1.cpp image.cpp
	g++ -o step2 step2.cpp image.cpp
