#(1) Name : Qirui Sun
#(2) USC ID Number : 1140685892
#(3) USC Email : qiruisun@usc.ed
#(4) Submission Date : 02/07/2021

all:
	g++ -o bilinear_demosaic.exe bilinear_demosaic.cpp image.cpp
	g++ -o hist_a.exe hist_a.cpp image.cpp
	g++ -o hist_b.exe hist_b.cpp image.cpp