#(1) Name : Qirui Sun
#(2) USC ID Number : 1140685892
#(3) USC Email : qiruisun@usc.ed
#(4) Submission Date : 03/12/2021

all:
	g++ -o reverse_geo reverse_geo_modification.cpp image.cpp
	g++ -o geo geo_modification.cpp image.cpp
