#(1) Name : Qirui Sun
#(2) USC ID Number : 1140685892
#(3) USC Email : qiruisun@usc.ed
#(4) Submission Date : 02/21/2021

all:
	g++ -o seper_fs seper_fs.cpp image.cpp
	g++ -o MBVQ MBVQ_fs.cpp image.cpp
