#(1) Name : Qirui Sun
#(2) USC ID Number : 1140685892
#(3) USC Email : qiruisun@usc.ed
#(4) Submission Date : 02/07/2021

all:
	g++ -o gaussian guassian_denoise.cpp image.cpp
	g++ -o uniform uniform_denoise.cpp image.cpp
	g++ -o bilateral bilateral_denoise.cpp image.cpp
	g++ -o noise_detection noise_detection.cpp image.cpp
	g++ -o median median_filter.cpp image.cpp