# (1) Name : Qirui Sun
# (2) USC ID Number : 1140685892
# (3) USC Email : qiruisun@usc.ed
# (4) Submission Date : 02/21/2021

all:
	g++ -o random random_dithering.cpp image.cpp
	g++ -o fix fix_dithering.cpp image.cpp
	g++ -o error_diffusion_FS error_diffusion_FS.cpp image.cpp	
	g++ -o error_diffusion_JJN error_diffusion_JJN.cpp image.cpp
	g++ -o error_diffusion_stucki error_diffusion_stucki.cpp image.cpp		